### PR TITLE
initial_states_mapper to circumvent when Inkling scenarios don't match 

### PR DESCRIPTION
**Pull request by journeyman-msft**
# Pull Request Template

PR song: https://www.youtube.com/watch?v=WJ8KdQGFjEU

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Quanser
- [ ] Cartpole

## Reviewer Tasks

List here all the tasks the reviewer needs to review:

- [ ] Test quanser
- [ ] Cartpole

**Test Configuration**:
* OS:
* Python Version:
* Bonsai SDK Version:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by journeyman-msft** [comment]
@akzaidi friendly reminder!

**Comment by akzaidi** [comment]
Thanks @journeyman-msft for the PR. I see the value of adding the mapper, as it makes SimConfigs in inkling a bit mroe intuitive. However, it adds a potentially redudant dictionary (should be covered by `initial_states`?). I'm wondering if we can just standardize on one of `initial_states` or `initial_states_mapper`, and avoid using the other.

Additionally, how would you continue using `test_random_policy` if the `yaml` has `initial_states_mapper`? Currently, `test_random_policy` does not utilize `initial_states_mapper` when creating the configurations for episode starts (it just uses episode_inits and initial_states:

```
test_random_policy(sim=sim, config={**episode_inits, **initial_states})
```

For instance, suppose you have the yaml as here:

```yaml
simulator:
  states:
    ["cart_position", "cart_velocity", "pole_angle", "pole_angular_velocity"]
  actions: ["command"]
  configs: ["pole_length", "pole_mass", "cart_mass"]
  # estimate these during training
  # e.g.,:
  episode_inits: { "pole_length": 0.4, "pole_mass": 0.055, "cart_mass": 0.31 }
  # e.g.,:  your simulator may need to know the initial state
  # before the first episode. define these here as a dictionary
  # you can include these in your Inkling scenarios during brain training
  initial_states:
    {
      "cart_position": 0,
      "cart_velocity": 0,
      "pole_angle": 0,
      "pole_angular_velocity": 0,
    }
  initial_states_mapper:
    {
      "initial_cart_position": "cart_position",
      "initial_cart_velocity": "cart_velocity",
      "initial_pole_angle": "pole_angle",
      "initial_pole_angular_velocity": "pole_angular_velocity"
    }
  policy: bonsai
  logging: enable
  workspace_setup: True
```

Which would work with an Inkling with `initial_` prefixes for the states in your SimConfig and scenarios, but does not work with our `ddm_predictor.test_random_policy` :(  We could do a join on the two keys before instantating `test_random_policy`, as we are already doing in `episode_start`, but that again shows the redundancy of both. Thoughts?

**Comment by journeyman-msft** [comment]
@akzaidi Good catch on the `test_random_policy`. It does work if a user specifies a config explicitly like so. This brings us back to "where do we want the master simulator configuration to come from if not bonsai?" I've been hardcoding it in for testing purposes. Happy to meet on this and discuss further.

image

Regarding the redundant `initial_states_mapper`, we already have a redundant `initial_states`. We have other examples that is allowed to have an empty config value for this. I agree it'd be cleaner though. Maybe we can try/catch using `initial_states`? We just want to be able to handle when theres a value, when there's not a value, and when there are strings as a mapper.

**Comment by akzaidi** [comment]
I don't want users hardcoding configs direclty into `ddm_predictor.py`, as that'll make it lose its genericity across examples.

Haha understood by the seeming redundancy of `initial_states`. Currently, we need one entrypoint for all initializations. We made the decisions to separate the config initializations (which are usually the configs used during log generation) from the state initializations, although for the purposes of the ddm they are equivalent. So we can't do without at least one of `episode_inits` and a mapper for initial states,, but we don't need all three of `episode_inits`, `initial_states` and the mapper

**Comment by journeyman-msft** [comment]
abandoning PR in favor of nested json

**Pull request closed without merging**
