### PR TITLE
WIP: Refactor with abstract classes to allow for different input / output pairs

### PR DESCRIPTION
**Pull request by akzaidi**
## Description

**PR Soundtrack**: [Peng Black Girls](https://www.youtube.com/watch?v=VW_UHYs3giU&ab_channel=COLORS)

New base classes for readers and for models that can be repurposed for different model designs. 

Fixes # (issue):
#16 , #10 , #8 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

There are a list of test functions under `tests`. An updated README describes new usage.

## Reviewer Tasks

List here all the tasks the reviewer needs to review:

- [x] Test `tests/`
- [x] Train new models using `python datamodeler2.py`. Create a new configuration file in `conf/model` or override defaults using CLI flags.
- [x] Run the simulator interface using `python sim_predictor.py`. Create a new configuration file in `conf/simulator` or override defaults using CLI flags.

**Test Configuration**:
* OS: macos
* Python Version: 3.7.7
* Bonsai SDK Version: 0.1.2

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by akzaidi** [comment]
@HosseinHeris , thanks for your updates!

Quick question: https://github.com/microsoft/datadrivenmodel/blob/alizaidi/refactor/skmodels.py#L47, should we be using PCA as a model type? Perhaps it's better suited as a preprocessor since we are mostly looking at supervised learning scenarios?

We are using scalar transformer as a separate object in the other model classes but here we are using it within the pipeline. I think I like the way it is here better. Probaby not going to change the other models but worth considering for the future.

**Comment by HosseinHeris** [comment]
Hey Ali,

I think PCA should be removed. I got confused to see it there. I agree it should be a preprocessor. Let's have it as another item for next sprint. I think it can be beneficial for some projects.

Hossein

**Comment by HosseinHeris** [comment]
@akzaidi : I just found redundancies in defining states , actions, and configs in the yml files located in the data and simulator folder. It is a minor issue but thought mentioning it.

**Comment by HosseinHeris** [comment]
@akzaidi : I also suggest to add name of the sim as prefix for model name when placing them in the models/boost/xgboost_model for example. This way, user may not confuse if he/she has two datasets. It is a minor issue to address in next iteration.

**Comment by HosseinHeris** [comment]
Re: previous comment: I see the saver filename. Then you may ignore it.

**Comment by HosseinHeris** [comment]
@akzaidi : I am having trouble with sklearn one:
basically I created the following "sklearn.yaml" file :
model:
  name: sklearn
  build_params:
    - model_type: SVR
  saver:
    - filename: models/boost/SVR_model
  sweep:
    - run: False
    - search_algorithm: bayesian
    - num_trials: 3
    - scoring_func: r2

but I ma getting the following error:
Traceback (most recent call last):
  File "datamodeler2.py", line 33, in main
    scale_data = cfg["model"]["build_params"][7]["scale_data"]
omegaconf.errors.ConfigIndexError: list index out of range
        full_key: model.build_params[7]
        reference_type=Optional[List[Any]]
        object_type=list

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by HosseinHeris** [comment]
@akzaidi : I tested on windows.  Everything looks great. I experience a small issue with scikitlearn that will discuss with you shortly.

**Pull request merged**
